import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xam Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <head>
        <meta name="google-site-verification" content="4Wn2rZJZjnWhpUL56NKhgvfPH0cJGvGNFVmq3t13M58" />
        </head>
        
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black relative `}
        >
          {children}
          <Toaster />

          <footer >
          <Footer/>
          </footer>
          
        </body>
      </AuthProvider>
    </html>
  );
}
